# 3 Vectorized Operations, Broadcasting, and Basic Linear Algebra in Numpy

Vectorization is applying the same operation to every element within an array, or multiple arrays. Numpy performs vectorized operations much faster and utilizing less memory (in most cases) than iterating through each element in a for loop. Vectorized operations are essential to linear algebra, which form the basis of machine learning, data mining, and processing. There are in general three type of vectorized operations in Numpy:
1) Vectorized Transformations
2) Vectorized Dimension Reduction
3) Vectorized Linear Algebra Operations 


In [1]:
import numpy

## 3.1 Vectorized Transformations in Numpy

The most basic way to think about vectorization is a transformation being applied to each element of an array which produces an array of the same shape. Below we will discuss a few common types of transformations: 
- scalar transformations,
- boolean operations,
- and mathematical functions.

### 3.1.1 Simple scalar transformations

Simple mathematical operations is performed between a multi-dimensional NumPy array (of any dimensionality) and a scalar value:

In [2]:
# 1 dimensional
x = numpy.array([20, 25, 30, 35])
print("x + 2 = ", x + 2)
print("x - 2 = ", x - 2)
print("x * 2 = ", x * 2)
print("x / 2 = ", x / 2)
print("x ** 2 = ", x ** 2)

x + 2 =  [22 27 32 37]
x - 2 =  [18 23 28 33]
x * 2 =  [40 50 60 70]
x / 2 =  [10.  12.5 15.  17.5]
x ** 2 =  [ 400  625  900 1225]


In [3]:
# N dimensional
x = numpy.arange(0, 2**3).reshape(2,2,2)
print( x )
print( "x * 2 = \n")
print(x*2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
x * 2 = 

[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]]


We can apply the scalar transformation on two (or multiple) arrays with the same shape: 

In [4]:
# same for two arrays:
numpy.array([1,2,3,4]) + numpy.array([2,2,2,2])

array([3, 4, 5, 6])

**Note:** Mind that such operations as above cannot be applied to Python lists. Lists are not designed for mathematical functions. You need a `for` loop to peform such operation son Python list which is costly in terms of computational times especially on large lists. For example:

In [5]:
# the * operator for python lists duplicates!
[1,2,3,4] * 2

[1, 2, 3, 4, 1, 2, 3, 4]

the + operator concatinates two python lists (it doesn't do addition):

In [6]:
[1,2,3,4] + [2,2,2,2]

[1, 2, 3, 4, 2, 2, 2, 2]

addition of a scalar doesn't work for a python list

In [7]:
[1,2,3,4] + 2

TypeError: can only concatenate list (not "int") to list

### 3.1.2 Boolean operations on arrays

As we've seen before, Boolean conditions can be applied to every element in an array. This is also a vectorized function. 

Several different conditions can be used, such as: equal to (==), not equal to (!=), greater than (>= or >), or smaller than (<= or <). 

In [8]:
# boolean operations on arrays
x = numpy.array([10, 20, 30, 14, 15, 16])
y = numpy.array([7, 5, 5, 7, 5, 7]) 
print("(x > 15) = ", x>15)
print("(y == 7) = ", y==7)

(x > 15) =  [False  True  True False False  True]
(y == 7) =  [ True False False  True False  True]


### 3.1.3 Mathematical functions

NumPy has a huge list of mathematical functions can be applied to multi-dimensional arrays. These operations are vectorized and thus applied to each element. Some examples are:

- numpy.sqrt(x): square root
- numpy.sin(x): sine
- numpy.cos(x): cosine
- numpy.tan(x): tangent
- numpy.exp(x): exponential
- numpy.log(x): natural logarithm

The complete list (includes many functions discussed later in this lecture): https://numpy.org/doc/stable/reference/routines.math.html


In [9]:
x = numpy.array([1, 2, 3, 4])
print("x = ", x)
print("sqrt(x) = ", numpy.sqrt(x))
print("sin(x) = ", numpy.sin(x) )
print("cos(x) = ", numpy.cos(x) )
print("tan(x) = ", numpy.tan(x) )
print("exp(x) = ", numpy.exp(x) )
print("log(x) = ", numpy.log(x) )

x =  [1 2 3 4]
sqrt(x) =  [1.         1.41421356 1.73205081 2.        ]
sin(x) =  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
cos(x) =  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
tan(x) =  [ 1.55740772 -2.18503986 -0.14254654  1.15782128]
exp(x) =  [ 2.71828183  7.3890561  20.08553692 54.59815003]
log(x) =  [0.         0.69314718 1.09861229 1.38629436]


Another set of common functions are rounding, including:
- numpy.round(x, decimals=2) : round to the nearest value
- numpy.floor(x): round down to an integer
- numpy.ceil(x): round up to an integer

In [10]:
x = numpy.random.uniform(0, 10, (2,5))
print("not rounded:", x)

x1 = numpy.round(x, decimals=2)
print("round:", x1)

x2 = numpy.floor(x)
print("floor:", x2)

x3 = numpy.ceil(x)
print("ceil:", x3)

not rounded: [[2.61108164 3.11602523 4.47984333 1.14114428 3.05433499]
 [9.22867396 1.42674823 9.4400946  9.13664951 1.69732604]]
round: [[2.61 3.12 4.48 1.14 3.05]
 [9.23 1.43 9.44 9.14 1.7 ]]
floor: [[2. 3. 4. 1. 3.]
 [9. 1. 9. 9. 1.]]
ceil: [[ 3.  4.  5.  2.  4.]
 [10.  2. 10. 10.  2.]]


#### 3.1.3.1 Comparing speed of numpy and python:

You might be asking yourself, are these really any faster than python? Let's check with the example of the sin() function:

In [11]:
a = numpy.random.uniform(-2, 2, 100000)
print(type(a))
print(a.size)

b = a.tolist()
print(type(b))
print(len(b))

<class 'numpy.ndarray'>
100000
<class 'list'>
100000


In [12]:
%%timeit 
a_sin = numpy.sin(a)

672 µs ± 12.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [13]:
# Since we do not want to use Numpy, we use alternatively the sin function from the math package
import math

In [14]:

%%timeit 
bb = []
for x in b:
    x_sin = math.sin(x)
    bb.append(x_sin)


8.41 ms ± 146 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


List comprehensions do not save python in this case (though it is faster):

In [15]:
%%timeit 
bb_comprehension = [math.sin(x) for x in b]

7.02 ms ± 71.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### 3.1.4 Other useful vectorized transformations

Numpy provides other functions that perform vectorized operations across arrays that are not traditional mathematical functions but can be very useful. For example:

- numpy.cumsum(x): returns an array containing the cumulative sum of the original elements
- numpy.cumprod(x): returns an array containing the cumulative propduct of the original elements 
- numpy.diff(x): returns an array containing the difference between each subsequent element (changes the number of items!)


In [16]:
x = numpy.array([1, 4, 7, 2])
print( x )
print( numpy.cumsum(x) )
print( numpy.cumprod(x) )
print( numpy.diff(x) )


[1 4 7 2]
[ 1  5 12 14]
[ 1  4 28 56]
[ 3  3 -5]


**Note:** Of course, the `diff` function cannot be considered as a vectorized transformation. But why?

## 3.2 Vectorized dimension reduction

Vectorized dimension reduction operations reduce the dimensionality of the input array. For example sum takes as input an array and returns a single value.

In [17]:
print( numpy.sum(numpy.array([10, 20, 30])) )

60


Here is the list of some useful vectorized dimension reduction functions in Numpy:
 
- numpy.sum(x)
- numpy.min(x)
- numpy.argmin()
- numpy.max()
- numpy.argmax()
- numpy.median(x)
- numpy.mean(x)
- numpy.average(x, weights= ) : (weighted) average
- numpy.std(x) : standard deviation
- numpy.var(x) : variance

In [18]:
x = numpy.array([[1, 6, 5], [2, 7, 8]])

# functions applied to the entire array:
print("sum:", x.sum())
print("minimum:", x.min(), "and index of minimum:", x.argmin())
print("maximum:", x.max(), "and index of maximum:", x.argmax())

sum: 29
minimum: 1 and index of minimum: 0
maximum: 8 and index of maximum: 5


### 3.2.1 Specifying subsets of dimensions

Many functions that reduce the number of dimensions can be also applied to a specific subset of dimensions. These functions have an optional parameter which is called `axis` (if no value for `axis` is provided then the function is applied to the whole array). 
For a two dimensional array (rows and columns), when `axis=0` then the function is applied aross rows (the left-most dimension) and the value for each column is returned. When `axis=1` then the function is applied across columns (the right-most dimension) and the value for each row is returned.



In [19]:
# functions applied to only one dimension of the array:
print("column sums:", x.sum(axis=0))
print("row sums:", x.sum(axis=1))
print("minimum per column:", x.min(axis=0))
print("maximum per row:", x.max(axis=1))

column sums: [ 3 13 13]
row sums: [12 17]
minimum per column: [1 6 5]
maximum per row: [6 8]


The same logic for `axis` applies to multi-dimensional arrays. When `axis=0` the left-most dimension is is computed across (and thus is not in the returned array). Higher values of `axis` will compute across dimensions further right:

In [24]:
x = numpy.random.random((10, 15, 20, 25))

print(x.shape)
print("Axis 0", x.max(axis=0).shape) # compute across left-most dimension
print("Axis 1", x.max(axis=1).shape) # compute across 2nd from left dimension
print("Axis 2", x.max(axis=2).shape) # compute across 3rd from left dimension
print("Axis 3", x.max(axis=3).shape) # compute across 4th from left dimension

(10, 15, 20, 25)
Axis 0 (15, 20, 25)
Axis 1 (10, 20, 25)
Axis 2 (10, 15, 25)
Axis 3 (10, 15, 20)


### 3.2.2 Ignoring NaN values

Many similar functions exist which ignore NAN. These functions are called: `nanmedian`, `nanmean`, `nanstd`, `nanvar`, etc. For more statistical functions in numpy: http://docs.scipy.org/doc/numpy/reference/routines.statistics.html

### 3.2.3 More complex transformations

One can combine different types of vectorized transformations to implement more complex transformations which are very common in machine learning. For example:

- Standardization: `z = (x - mean(x)) / std(x)`. Standardized values (z-scores) have zero mean and unit standard deviation. Standardization is often used before applying machine learning algorithms. 

- Feature scaling: `y = (x - min(x)) / (max(x) - min(x))`, this brings the score in the range 0 to 1.


## Exercise 3.1

- Define function `to_cm` which takes a vector of measurements in inches and converts them to centimeters (1 inch is 2.54cm).
- Define function `to_celsius` which takes a vector of measurements in Fahrenheit and converts them to Celsius: C = (F-32)/1.8


In [26]:
def to_cm(x):
    x = x * 2.54
    return x

In [30]:
to_cm(x)

array([ 0.  ,  2.54,  5.08,  7.62, 10.16])

In [28]:
def to_celsius(x):
    x = (x - 32) / 1.8
    return x

In [29]:
to_celsius(100)

37.77777777777778

## Exercise 3.2

The function `softmax` is often used in machine learning and statistics to convert a vector of arbitrary numbers into a vector of probabilities summing up to 1. Softmax works by computing the exponential of each number, and then dividing each number by the sum of the exponentials:

$$ \mathrm{softmax}(x_i): \frac{\exp(x_i)}{\sum_{k=1}^N \exp(x_k)} $$

Implement the softmax function. Verify that in the resulting vector all number are between 0 and 1. Verify that the resulting numbers sum up to $1$. Try implementing a version that relies on for loops and a version that is vectorized.

In [33]:
# assume a one-dimensional array
from math import exp2
def softmax(x):
    x = numpy.exp2(x) / sum(exp2(x))
    pass

a = numpy.arange(0, 5) 
b = softmax(a)

TypeError: only size-1 arrays can be converted to Python scalars

## 3.3 Vectorized Linear Algebra Operations

Linear algebra is a branch of mathematics dealing with vector spaces. Linear algebra operations are very useful when manipulating numeric datasets. Using these operations often allows us to avoid writing explicit loops, and thus make our code more readable, more concise, and faster to execute. Linear algebra is deeply connected to vectorization but has specific mathematical properties. Many machine learning algorithms and methods are specified to be effieciently performed using linear algebra, and we will introduce a few in the following sections.

The vectorization principle in Numpy can be used to implement more complext linear algebra operations on multiple multi-dimensional arrays.

### 3.3.1 Vectorized element-wise linear algebra operations on multiple arrays with same shape

We can perform efficienly the most basic element-wise linear algebra operations such as addition, subtraction, multiplication, and division on multiple arrays using vectorization concept in Numpy. The limitation is that all operands must have exactly the same shape.

In [ ]:
x = numpy.array([10, 20, 30, 40])
y = numpy.array([5, 7, 52, 34])

print("y - x = ", y - x)
print("x + y = ", x + y)
print("x * y = ", x * y)
print("x / y = ", x / y)

These vectorized functions also work for matricies and N-dimensional arrays of the same size.

In [ ]:
x = numpy.array([[10, 20, 25], [30, 40, 50]])
y = numpy.array([[5, 7, 10], [52, 34, 17]])

print(y - x)
print(x + y)
print(x * y)
print(x / y)

### 3.3.2 Broadcasting for vectorized element-wise linear algebra operations on multiple arrays with different shapes

Besides operations between arrays of the same shape, it is sometimes possible to perform operations between arrays of different shapes. In numpy performing vectorized operations on arrays with different shapes is called broadcasting. Broadcasting enables NumPy to treat arrays with different shapes during vectorized operations. 

Broadcasting between two multidimensional arrays of different sizes can be done but is complex. Numpy is smart about figuring out if two arrays can be aligned such that dimensions have the same number of elements to perform the desired operation. The two arrays are “broadcastable” if for each dimension:
 - they have equal number of elements, otherwise
 - for non-equal dimensions, either of them must be 1.

If two arrays are broadcastabe, then broadcasting is performed in five steps:

1) Shift: If the number of dimensions is different, shift the array with smaller dimension to the right.
2) Match: Add 1 to the left so that the arrays have the same number of dimensions.
3) Check: Check if they are broadcastable: if yes continue to the next step.
4) Stretch: “copy” the single dimensions to match dimensions between the arrays.
5) Perform the operation.

For example:

In [ ]:
a = numpy.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
print(a.shape)
b = numpy.array([1.0, 2.0, 3.0])
print(b.shape)
c = a + b 
print(c, c.shape)

![second example](https://numpy.org/doc/stable/_images/broadcasting_2.png)

In [ ]:
a = numpy.array([[0.0], [10.0], [20.0], [30.0]])
print(a.shape)
b = numpy.array([1.0, 2.0, 3.0])
print(b.shape)
c = a + b
print(c, c.shape)


![second example](https://numpy.org/doc/stable/_images/broadcasting_4.png)

Some examples that do broadcast:

```
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```

Some examples that do not broadcast:

```
A      (1d array):  3
B      (1d array):  4 # trailing dimensions do not match

A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched
```

**Careful:** Often broadcasting this can result in unexpected behavior that does not produce an error if arrays are not the dimensionality you expect. Because of this, it is important to confirm the dimensionality of arrays match your expectations throughout your analysis. For more information about Broadcasting:
http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

## Exercise 3.3

Generate a numpy array of length 5 containing random integers between 1 and 15. Use the functions `numpy.reshape` and broadcasting to build a two-dimensional array where each element (i, j) is the product of the ith and jth elements of the initial array.

So, for example, the two dimensional array's first element should be `a[0]` * `a[0]`, then `a[0]` * `a[1]` and so forth.


### 3.3.3 Linear Algebra Operations on Vectors and Matrices

#### 3.3.3.1 Vector Multiplication (using dot product)

The dot product between two matrices returns a scalar value that is the sum of multiplying each element of the two matrices together. In numpy the dot product (or scalar product) between two vectors (one-dimensional arrays) is treated as
a special case of multi-dimensional array multiplication. 

The definition of the dot product between two vectors $a$ and $b$ is:

$$\langle a, b\rangle = \sum_{i=1}^N ab$$

Other notations that you will come across for this operation are:

$a \cdot b$

$a^T b$

In [ ]:
a = numpy.random.uniform(-10,10,100)
b = numpy.random.uniform(-10,10,100)

c = a * b # Element-wise multiplication
d = a.dot(b) # Dot product

print(c)
print('#########################')
print(d)

#### 3.3.3.2 Matrix multiplication (using dot product)

Matrix multiplication does not produce a single scalar. Instead, it produces a full matrix of values calculated using the same dot product formula from above. Each column in the first matrix is paired with a row in the second matrix and the dot product between those two vectors is a value in the resulting matrix. 
Because of this, the number of columns in the first matrix needs to be equal to the number of rows in the second matrix. For matrices $A_{m\times n}$ and $B_{n \times p}$, the resulting matrix will be $C_{m \times p}$. The value of each entry in the resulting matrix $C$ is the result of computing the dot product between a row from $A$ and a column from $B$:

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Matrix_multiplication_diagram_2.svg/470px-Matrix_multiplication_diagram_2.svg.png)

The equation for calculating each cell is the same as the vector dot product formula:

$$
C_{i,j} = \sum_{k=1}^n A_{i,k}B_{k,j}
$$

In order to compute the dot product between two matricies a and b, we use:

```python
numpy.dot(A, B)
```
or

```python
A.dot(B)
```

In [ ]:
A = numpy.random.random([4, 10])
B = numpy.random.random([10, 3])
C = A.dot(B)
print(C, C.shape)

## Exercise 3.4

- Create a random matrix $A_{3\times 4}$ and another random matrix $B_{4 \times 2}$. Multiply AB.  
- Create a random matrix $C_{3\times 3}$ and $D_{3\times3}$. Multiply CD. Multiply DC. Is matrix multiplication commutative?
- Create a identity matrix $I_{3\times 3}$.  Multiply IC, CI, DI, ID. What do you notice?
- What will be the result of multiplying a matrix $Z_{m\times n}$ by a matrix $O_{n \times p}$ whose all entries are zero? Check your answer using some examples.

#### 3.3.3.3 Matrix Transpose
We have already encountered matrix transpose when we discussed reshaping numpy arrays. Transposing a matrix simply means making the rows into columns and columns into rows. This is often required to align a matrix properly for matrix multiplication.

The mathematical notation for the transpose of matrix $A$ is $A^T$. If $A$ is $m \times n$ then $A^T$ is $n \times m$. The values are:

$$A^T_{i,j} = A_{j,i}$$

The function to compute the transpose of matrix A is either `numpy.transpose(A)` or simply `A.T`.

In [ ]:
A = numpy.random.random([4, 10])
print(A.shape)
B = A.T
print(B.shape)

print(numpy.allclose(A, B.T))


#### 3.3.3.4 Matrix Inversion
When using scalar values, dividing by a number $n$ is straightforward: it mearly requires multiplying by $\frac{1}{n}$. This value is the multiplicative inverse (aka reciprocal) $n$ is $\frac{1}{n}$ and can also written as $n^{-1}$. 

The inverse has certain properties, including:
- $n^{-1}n = 1$
- $(n^{-1})^{-1} = n$

For matricies, there is an analogous concept. The inverse of a matrix $A$ is written $A^{-1}$ and it satisfies three critical properties:

- $A^{-1}A = I$ where $I$ is the $m \times m$ identity matrix
- $(A^{-1})^{-1} = A$
- $(A^T)^{-1} = (A^{-1})^T$

Not all matrices are invertible: a matrix needs to be square (that is, the number of rows must equal the number of columns), and its [determinant](https://en.wikipedia.org/wiki/Determinant) needs to be non-zero. 

Computing the inverse of a matrix is critical for many data science techniques, including computing the best fitting parameter weights for ordinary least squares linear regression (an example we will look at next). We will use the function `inv` from the `linalg` submodule to compute this.


In [ ]:
from numpy.linalg import inv
A = numpy.random.uniform(0,1,(3,3))
print(A)
print()
print(inv(A))

## Exercise 3.5

Generate a $3 \times 3$ matrix of random values named A.

Part A: Verify that $A^{-1}A = I$, where $I$ is the $m \times m$ identity matrix

Part B: Verify that $(A^{-1})^{-1} = A$

Part C: Verify that $(A^T)^{-1} = (A^{-1})^T$