In [4]:
import numpy

## Exercise 3.1

- Define function `to_cm` which takes a vector of measurements in inches and converts them to centimeters.
- Define function `to_celsius` which takes a vector of measurements in Fahrenheit and converts them to Celsius: C = (F-32)/1.8


In [ ]:
def to_cm(x):
    return x * 2.54

print(to_cm(100))
print(to_cm(0))
print(to_cm(-5))

In [ ]:
def to_celsius(x):
    return (x - 32) / 1.8

to_celsius(212)

## Exercise 3.2

The function `softmax` is often used in machine learning and statistics to convert a vector of arbitrary numbers into a vector of probabilities summing up to 1. Softmax works by computing the exponential of each number, and then dividing each number by the sum of the exponentials:

$$ \mathrm{softmax}(x_i): \frac{\exp(x_i)}{\sum_{k=1}^N \exp(x_k)} $$

Implement the softmax function. Verify that in the resulting vector all number are between 0 and 1. Verify that the resulting numbers sum up to $1$. Try implementing a version that relies on for loops and a version that is vectorized.

In [ ]:
# assume a one-dimensional array
def softmax(x):
    exp_x = numpy.exp(x)
    sum_exp_x = numpy.sum(exp_x)
    sm = exp_x / sum_exp_x
    return sm

In [ ]:
a = numpy.random.random(24)
b = softmax(a)

print(numpy.sum(b))
print(numpy.max(b))
print(numpy.min(b))

In [ ]:
import math

def for_loop_softmax(x):
    exp_x = []
    for item in x:
        exp_x.append(math.exp(item))
    
    sum_exp_x = 0
    for item in exp_x:
        sum_exp_x += item
    
    sm = []
    for item in exp_x:
        sm.append(item / sum_exp_x)
    
    return sm
    

In [ ]:
b = for_loop_softmax(a)

print(numpy.sum(b))
print(numpy.max(b))
print(numpy.min(b))

### Bonus

checking how long it takes (on average) to run these solutions:

In [ ]:
%%timeit
a = numpy.random.random(10000)
b = softmax(a)

In [ ]:
%%timeit
a = numpy.random.random(10000)
b = for_loop_softmax(a)

## Exercise 3.3

Generate a numpy array of length 5 containing random integers between 1 and 15. Use the functions `numpy.reshape` and broadcasting to build a two-dimensional array where each element (i, j) is the product of the ith and jth elements of the initial array.

So, for example, the two dimensional array's first element should be `a[0]` * `a[0]`, then `a[0]` * `a[1]` and so forth.


In [5]:
a = numpy.random.randint(1, 15, 5)
print(a, a.shape)
print()

[ 2 13  4 13  3] (5,)



In [6]:
b = a.reshape((5,1))
print(b, b.shape)
print()

[[ 2]
 [13]
 [ 4]
 [13]
 [ 3]] (5, 1)



In [7]:
c = a * b
print( c )

[[  4  26   8  26   6]
 [ 26 169  52 169  39]
 [  8  52  16  52  12]
 [ 26 169  52 169  39]
 [  6  39  12  39   9]]


## Exercise 3.4

- Create a random matrix $A_{3\times 4}$ and another random matrix $B_{4 \times 2}$. Multiply AB.  
- Create a random matrix $C_{3\times 3}$ and $D_{3\times3}$. Multiply CD. Multiply DC. Is matrix multiplication commutative?
- Create a identity matrix $I_{3\times 3}$.  Multiply IC, CI, DI, ID. What do you notice?
- What will be the result of multiplying a matrix $Z_{m\times n}$ by a matrix $O_{n \times p}$ whose all entries are zero? Check your answer using some examples.


In [8]:
a = numpy.random.random((3,4))
b = numpy.random.random((4,2))

print(a.dot(b))

[[0.76525439 0.58780943]
 [1.10527696 0.49199262]
 [0.96164341 0.31269419]]


In [9]:
c = numpy.random.random((3,3))
d = numpy.random.random((3,3))

print (c.dot(d))
print()
print(d.dot(c))


[[0.2197035  0.30324203 0.2357344 ]
 [0.41111372 0.81947723 0.68746313]
 [0.15573571 0.29642409 0.24603191]]

[[0.24923057 0.49224319 0.35752086]
 [0.24388229 0.7802324  0.56229183]
 [0.19320718 0.3522438  0.25574967]]


In [ ]:
i = numpy.eye(3)

print(c)
print()
print(c.dot(i))
print()
print(i.dot(c))

print('=========================')

print(d)
print()
print(d.dot(i))
print()
print(i.dot(d))

In [ ]:
m = 5
n = 4
p = 3
z = numpy.zeros([m,n])
o = numpy.zeros([n,p])

result = z.dot(o)

print(result, result.shape)

## Exercise 3.5

Generate a $3 \times 3$ matrix of random values named A.

Part A: Verify that $A^{-1}A = I$, where $I$ is the $m \times m$ identity matrix

Part B: Verify that $(A^{-1})^{-1} = A$

Part C: Verify that $(A^T)^{-1} = (A^{-1})^T$

In [ ]:
from numpy.linalg import inv

a = numpy.random.random((3,3))
a_inv = inv(a)


print(a.dot(a_inv))
print()
print(numpy.eye(3))
print()
print(numpy.allclose(a.dot(a_inv), numpy.eye(3)))


In [ ]:
print(a)
print()
print(a_inv)
print()
print(inv(a_inv))
print()
print(numpy.allclose(a, inv(a_inv)))


In [ ]:
print(inv(a.T))
print()
print(inv(a).T)
print()
print(numpy.allclose(inv(a.T), inv(a).T))
