## Week 3 Daily Exercise 5

Create three matrices: A 4x4 matrix of random numbers ($A$), a 1x4 matrix of ones ($B$), and a 4x1 matrix of ones ($C$).
Calculate the following:


*   The sum over the rows of $A$ (called $W$)
*   The sum over the columns of $A$ (called $X$)
*   Dot product $AC$ (called $Y$)
*   Dot product $BA$ (called $Z$)

How are $W$, $X$, $Y$, and $Z$ related? Why?

### Solution:

In [1]:
import numpy

In [2]:
#create matrices
numpy.random.seed( 42 )
A = numpy.random.randint(1,10,(4,4))
B = numpy.ones((1,4))
C = numpy.ones((4,1))

In [3]:
print(A)
print()
print(B)
print()
print(C)

[[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]]

[[1. 1. 1. 1.]]

[[1.]
 [1.]
 [1.]
 [1.]]


In [4]:
# this computes the sum across the rows of A

W = numpy.sum(A, axis = 1)
print(W)

[24 25 25 16]


In [5]:
# this computes the sum across the columns of A

X = numpy.sum(A, axis = 0)
print(X)

[22 17 28 23]


In [6]:
# this computes the dot product of A and C

Y = A.dot(C)
print(Y)

[[24.]
 [25.]
 [25.]
 [16.]]


In [7]:
# this computes the dot product of B and A

Z = B.dot(A)
print(Z)

[[22. 17. 28. 23.]]


The values of $W$ and $Y$, as well as $X$ and $Z$ are the same (though the shapes differ).

This is because computing the dot product with a vector of ones is the same as computing the sum along a dimension.