In [2]:
import numpy as np

# Daily Exercise 1
Write a function that takes three positive integer parameters size, start, and step and returns a square two-dimensional matrix with size entries per dimension. The values in the matrix should all be zero except values on the principle diagonal. The first value on this diagonal should be start and each subsequent value should be step larger.
## My solution with a loop

In [25]:

def build_nifty_matrix(size, start, step):
    a = np.eye(size)
    i = 0
    for row in a:
        row[i] = start + (step * i)
        i += 1
    return a

## Solution provided
This is better because it is a vectorized operation making use of the fact that the other values are zero. Thus, multiplying the a vector by the b matrix provides the solution

In [31]:
import numpy as np

def build_nifty_matrix(size, start, step):
    a = np.arange(start, start + step * size, step)
    b = np.eye(size)
    return a, b, a*b


In [32]:
print(build_nifty_matrix(3, 42, 2))

(array([42, 44, 46]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]), array([[42.,  0.,  0.],
       [ 0., 44.,  0.],
       [ 0.,  0., 46.]]))


In [27]:
print(build_nifty_matrix(5, -1, 100))

[[ -1.   0.   0.   0.   0.]
 [  0.  99.   0.   0.   0.]
 [  0.   0. 199.   0.   0.]
 [  0.   0.   0. 299.   0.]
 [  0.   0.   0.   0. 399.]]


# Daily Exercise 2
By default, the reshape function uses the 'C' order to fill in multi-dimensional arrays (see https://numpy.org/doc/stable/reference/generated/numpy.reshape.htmlLinks to an external site. for more information). ‘C’ means to read/write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest. To test this, use the arange function to create a one-dimensional array with values between 2 and 12 with step size 2. Then reshape it to a 2 by 3 two-dimensional array. Check the order of numbers in rows and columns.

Now, write code that fills in values the other way around when reshaping, i.e. the first axis index should change fastest. Print the results and compare them with the outputs of the previous setting.

## My solution
Correct according to solution provided

In [14]:
a = np.arange(2, 13, 2).reshape((2,3))

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
b = np.arange(2, 13, 2).reshape((2,3), order="F")

array([[ 2,  6, 10],
       [ 4,  8, 12]])

# Daily Exercise 3
Create two 4x4, 2-dimensional arrays: one containing only zeros, the other containing only ones.

Stack them using a vertical stack, then reshape the stacked array into a 3-dimensional array. Now, use array indexing to retrieve only ones from the stacked array.

Now reshape the stacked array into a 3-dimensional array in such a way that the first (the leftmost) dimension consists of only ones or zeros, but not both. Again, use array indexing to retrieve only ones from the reshaped 3D array.
## My solution

Beetje cursed? The solution provided is bs and does not match with what is asked. Solution asks to stack, reshape, THEN retrieve only ones. Which the solution DOES NOT. 

In [44]:
a = np.ones((4,4))
b = np.zeros((4,4))

c = np.vstack((a, b))
print(c.ndim)
c = c.reshape(4, 2, 4)
print(c[0:2, ])

d = c.reshape(2, 16, 1)
print(d[0])


2
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
