# 2. Multidemensional Arrays


An array is an ordered and structured collection of elements. Arrays are structured around the number of dimensions they contain, as well as how many elements exist along each dimension. Today we will focus on arrays that are more than one dimension.

A one-dimensional array that contains six elements looks like:

  4 5 6 7 8 9

Or we could have a two-dimensional array that contains six elements with two rows and three columns:

  4 5 6
  
  7 8 9

In general, an array can be $n$-dimensional. One way to think of $n$-dimensional arrays in terms of the bookshelf analogy:

- 1d array is a single row of a bookshelf, where a book can be identified by its position in the row
- 2d array is the whole bookshelf, where a book can be identified by its row number and its position in the row
- 3d array is a room full of bookshelves, where a book can be identified by the number of the bookshelf, row, and position in the row
- 4d array is a library with rooms with bookshelves, where a book can be identified by the room, bookshelf, row and position in the row
- ...and so on...

The constraints for multi-dimensional numpy arrays are the same as for one-dimensional arrays: 
- all elements must be of the same type
- all elements are contiguous in memory to allow for fast computations

Similar to 1-dimensional arrays, we can use four methods to create multi-dimensional arrays:
- From Python lists and tuples
- From a file
- Using intrinsic Numpy functions
- Using functions in the random module in Numpy

In the ramaining, we will see examples on creating multi-dimensional Numpy arrays.

## 2.1 Creating multidemensional arrays 

### 2.1.1 Creating multidemensional arrays from Python lists and tuples

Last week we focused on creating arrays that contain one dimesion. We have learned about multiple attributes we can access to get insight about the array characteristics including:
- `x.ndim` : the number of dimensions.
- `x.shape` : the length of each dimension.
- `x.size` : the total number of elements.
- `x.dtype`: the datatype of the elements in the array.

In [1]:
import numpy

b = numpy.array([1, 2, 3])
print( b )
print( b.ndim, b.shape, b.size, b.dtype )

[1 2 3]
1 (3,) 3 int32



When creating two dimensional arrays, the simplist way to do so is based on python structures. Specifically, create the numpy array based off a python list, where each element of the list is another list. In this case the outer list is a list of the rows and each inner list specifies the elements of that row.

In [2]:
a = numpy.array([[1, 3, 6, 5], [2, 4, 3, 0]])
#a = numpy.array(((1, 3, 6, 5), (2, 4, 3, 0)))

print( a )
print( a.ndim, a.shape, a.size, a.dtype )

[[1 3 6 5]
 [2 4 3 0]]
2 (2, 4) 8 int32


A true 2-dimensional array (also called a matrix) is created only if the number of elements in each row is the same across all rows. Otherwise, a one-dimensional numpy array of python lists is created:

In [5]:
"""b = numpy.array([[1, 3, 6, 5], [2, 4, 3]])

print( b )
print( b.ndim, b.shape, b.size, b.dtype )"""

'b = numpy.array([[1, 3, 6, 5], [2, 4, 3]])\n\nprint( b )\nprint( b.ndim, b.shape, b.size, b.dtype )'


N-dimensional arrays can be created in the same way as two-dimensional arrays but with more nested lists:

In [6]:
# create a three dimensional array:
z1 = numpy.array([[[1, 3], [2, 4]], [[11, 13], [12, 14]] ])

# dimensions/shape/size of the array:
print(z1)
print( "Number of dimensions:", z1.ndim )
print( "Length of each dimension:", z1.shape )
print( "The total number of elements:", z1.size )

[[[ 1  3]
  [ 2  4]]

 [[11 13]
  [12 14]]]
Number of dimensions: 3
Length of each dimension: (2, 2, 2)
The total number of elements: 8


## Exercise 2.1

First, create a 2x3x2 three-dimensional array (you decide which values to include). Then, create 2x2x3 three-dimensional array. Verify the arrays have the same number of dimensions and elements but different shapes.

In [21]:
a = numpy.array([[[0, 1], [2, 5], [2, 5]], [[4, 5], [6, 7], [2, 5]]])
b = numpy.array([[[0, 1, 2], [2, 3, 4]], [[0, 1, 2], [4, 5, 8]]])

print(a)
print(b)
print("Ndim", a.ndim, b.ndim)
print("Ldim", a.shape, b.shape)
print("Size", a.size, b.size)

[[[0 1]
  [2 5]
  [2 5]]

 [[4 5]
  [6 7]
  [2 5]]]
[[[0 1 2]
  [2 3 4]]

 [[0 1 2]
  [4 5 8]]]
Ndim 3 3
Ldim (2, 3, 2) (2, 2, 3)
Size 12 12


### 2.1.2 Reading and writing multidimensional arrays from/to file

There are two major numpy based methods for saving objects: saving them as a text file, or as a numpy-specific binary file. The first option is very similar to a csv file, the second preserves the numpy structure (like python's pickle library). The way to use these methods are:

- `numpy.savetxt(filename, array)` : save a 1-dimensional or 2-dimensional array to a text file. 
- `numpy.save(filename, array)` : save an array to a binary file in numpy `.npy` format.

The corresponding functions for reading these formats are `numpy.loadtxt()` and `numpy.load()`.

In [22]:
# create a two dimensional array:
a = numpy.array([[1, 3, 6, 5], [2, 4, 3, 0]])
print(a, a.shape, a.dtype)

# saving the array in a text file
numpy.savetxt('textfile.txt', a, fmt='%d', delimiter=',')

[[1 3 6 5]
 [2 4 3 0]] (2, 4) int32


In [23]:
# loading a two dimensional array form the disk
b = numpy.loadtxt('textfile.txt', dtype='int', delimiter=',')
print(b, b.shape, b.dtype)

[[1 3 6 5]
 [2 4 3 0]] (2, 4) int32


In [24]:
# create a three dimensional array:
a = numpy.array([[[1, 3], [2, 4]], [[11, 13], [12, 14]] ])
print(a, a.shape, a.dtype)

# saving the array in a binary file
numpy.save('binaryfile.npy', a)

[[[ 1  3]
  [ 2  4]]

 [[11 13]
  [12 14]]] (2, 2, 2) int32


In [25]:
# loading an array from a binary file
b = numpy.load('binaryfile.npy')
print(b, b.shape, b.dtype)

[[[ 1  3]
  [ 2  4]]

 [[11 13]
  [12 14]]] (2, 2, 2) int32


## Exercise 2.2

Part 1: Generate a one dimensional array. Save to disk as a text file, and as a npy file. Create a new array that is based on reading the array back from the text file, and a new array that is based on the npy file. Is the information preserved in both formats?

Part 2: Repeat part 1 with a two-dimensional array and then a three-dimensional array. What works and what does not?

Numpy format can save n-dimensional arrays while txt can only store up to 2D

In [38]:
a = numpy.array([1, 0])
numpy.savetxt("ex2.2.txt", a)
numpy.save("ex2.2.npy", a)

b0 = numpy.loadtxt("ex2.2.txt")
b1 = numpy.load("ex2.2.npy")

print(b0.shape, b0.ndim, b0.size)
print(b1.shape, b1.ndim, b1.size)

c = numpy.array([[1, 0], [2, 0]])
numpy.savetxt("c.txt", c)
numpy.save("c.npy", c)

d0 = numpy.loadtxt("c.txt")
d1 = numpy.load("c.npy") 
print(d0.shape, d0.ndim, d0.size)
print(d1.shape, d1.ndim, d1.size) 

e = numpy.array([[[1, 0], [2, 0]], [[2,0], [3, 0]]]) 
#numpy.savetxt("e.txt", e)
numpy.save("e.npy", e)

#f0 = numpy.loadtxt("e.txt")
f1 = numpy.load("e.npy")
#print(f0.shape, f0.ndim, f0.size)
print(f1.shape, f1.ndim, f1.size)

(2,) 1 2
(2,) 1 2
(2, 2) 2 4
(2, 2) 2 4
(2, 2, 2) 3 8


### 2.1.3 Creating N-dimensional arrays using Numpy functions

Creating arrays by specifying nested lists of elements is tedious. Therefore, there are nice tools for creating mulit-dimensional arrays.

An empty array or an array with only zeros or ones can be created with the `empty`, `zeros` and `ones` functions. 
Be careful with the empty array. This is the fastest way to inialize an array but the content of the empty array can be anything (it will be whatever was already written in that location in memory).

The shape of the array is the input for these functions:


In [40]:
# create a one-dimensional empty array:
a = numpy.empty([3])
print(a, a.shape)

[1.37864029e-311 0.00000000e+000 6.47591605e-319] (3,)


In [41]:
# create two-dimensional array with only zeros:
b = numpy.zeros([2, 3])
print(b, b.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)


In [42]:
# create a four-dimensional array with only ones:
c = numpy.ones([2,2,2,2])
print(c, c.shape)

[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]] (2, 2, 2, 2)


An identity matrix is a two-dimensional square matrix (same number of rows and columns) in which all values are zeros, except for ones along the diagonal. 
The identity matrix can be created with the `eye(n)` function. Since the identity matrix is always a square, only one input parameter is needed to create the 2-dimensional matrix.

In [43]:
# create n by n identity matrix:
print(numpy.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 2.1.4 Creating random N-dimensional arrays
Specifying the shape of the array, we can create multi-dimensional arrays with any arbitrary dimensions:


In [45]:
a = numpy.random.random([2,2])
print(a, a.shape)


[[0.70912826 0.33832168]
 [0.43069465 0.73810748]] (2, 2)


In [46]:
a = numpy.random.randint(0, 100, [10,2])
print(a, a.shape)


[[53 24]
 [18 33]
 [ 8 14]
 [39  5]
 [97 12]
 [10 12]
 [84 53]
 [82 38]
 [98 46]
 [13 38]] (10, 2)


In [47]:
a = numpy.random.uniform(0, 100, [3,2,2])
print(a, a.shape)


[[[30.63395114 35.06731165]
  [86.00021025 35.23479675]]

 [[43.65082493 92.29964174]
  [46.75193842 25.68873783]]

 [[61.07728822 21.78187135]
  [ 1.97684496 63.62463098]]] (3, 2, 2)


In [48]:
a = numpy.random.normal(0, 5, [2,2])
print(a, a.shape)

[[ 0.59099417 -5.52282788]
 [-1.68611381 -8.10288014]] (2, 2)


## 2.2 Array stacking and splitting

More complex arrays can be created by combining two or more one-dimensional arrays. This is called vector stacking. There are two functions to stack arrays and they produce arrays with different shapes:

- horizontal stack: `numpy.hstack([x, y, z])`
- vertical stack: `numpy.vstack([x, y, z])`

In [49]:
x = numpy.arange(0, 5)                     
y = numpy.arange(5, 10)   
z = numpy.arange(10, 15)

In [50]:
print("Horizontal stack: " )
a = numpy.hstack([x, y, z])
print(a)
print(a.shape)

Horizontal stack: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)


In [51]:
print("Vertical stack: ")
a = numpy.vstack([x, y, z])
print(a)
print(a.shape)

Vertical stack: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)


The opposite of vector stacking is to split a two-dimensional array into a list of one-dimensional arrays (vectors). The first argument is the 2D array and the second argument is the number of 1D arrays to create. It is important that that the number of pieces you want is possible given the number of rows or columns. Two different ways of splitting:
- Vertical split: `numpy.vsplit(x, N)`
- Horizontal split: `numpy.hsplit(x, N)`


In [52]:
a = numpy.arange(0, 5)                     
b = numpy.arange(5, 10)   
c = numpy.arange(10, 15)
d = numpy.vstack([a, b, c])

print(d, d.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5)


In [53]:
print("\nVertical split: ")
print( numpy.vsplit(d, 3) )


Vertical split: 
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]])]


In [54]:
print("\nHorizontal split: ")
print( numpy.hsplit(d, 5) )


Horizontal split: 
[array([[ 0],
       [ 5],
       [10]]), array([[ 1],
       [ 6],
       [11]]), array([[ 2],
       [ 7],
       [12]]), array([[ 3],
       [ 8],
       [13]]), array([[ 4],
       [ 9],
       [14]])]


## 2.3 Reshaping arrays

We can use `reshape()` function to rearrange the elements of a multi-dimensional numpy array along its different dimensions. 

However, it is critical that the the total number of elements matches. For example, if the length of the initial list is 24, then we can reshape it to a 4 by 6 matrix. We could also transform it into a three-dimensional 2 by 3 by 4 matrix.

When reshaping, the shape of the new array is specificed as a tuple that lists the number of entries along each dimension. For creating a two-dimensional array, the first element in the tuple will be the number of rows, the second is the number of columns.

In [55]:
# reshape into a two dimensional array:
y = numpy.arange(2, 14, 2)
print(y)
print( y.ndim, y.shape, y.size)

z = y.reshape((2, 3))
print( z )
print( z.ndim, z.shape, z.size)

[ 2  4  6  8 10 12]
1 (6,) 6
[[ 2  4  6]
 [ 8 10 12]]
2 (2, 3) 6


In a three-dimensional array, however, the first value specifies the number of "rows", the second specifies the number of columns and the third specifies the layers.

In [56]:
# reshape into a three dimensional array:
z2 = numpy.random.random([6,4]).reshape((2, 3, 4))

# dimensions/shape/size of the array:
print( z2 )
print( "Number of dimensions:", z2.ndim )
print( "Length of each dimension:", z2.shape )
print( "The total number of elements:", z2.size )

[[[0.86083002 0.38181301 0.21413493 0.53913839]
  [0.05711323 0.36752536 0.14489897 0.59579943]
  [0.75940439 0.61585179 0.10138585 0.64417888]]

 [[0.58733404 0.60230079 0.18434085 0.76138925]
  [0.34406932 0.10487464 0.159      0.37638828]
  [0.58248774 0.91535861 0.11934975 0.12458473]]]
Number of dimensions: 3
Length of each dimension: (2, 3, 4)
The total number of elements: 24


## Exercise 2.3

First, create a 2x3x2 three-dimensional array containing random values from a normal distribution. Then, reshape that array into a 2x2x3 three-dimensional array. Verify the shape has changed.

In [70]:
a = numpy.random.normal(0, 10, 12).reshape((2, 3, 2))
display(a)
b = a.reshape(2, 2, 3)
display(b)

array([[[ -3.89092119,   3.16464689],
        [ -6.10373638,   0.60852781],
        [  7.32199706, -14.09883682]],

       [[  3.55516345,  -1.94834942],
        [-11.35267129,  -8.87936661],
        [-12.32126945,  -6.54859014]]])

array([[[ -3.89092119,   3.16464689,  -6.10373638],
        [  0.60852781,   7.32199706, -14.09883682]],

       [[  3.55516345,  -1.94834942, -11.35267129],
        [ -8.87936661, -12.32126945,  -6.54859014]]])

### 2.3.1 Shallow vs. deep copying

Reshaping a numpy array is (usually) blazingly fast. This is because numpy does not copy all the elements in memory. Instead, a new variable points to the same memory location (this is called a shallow copy). This can intruduce unanticipated behavior:

In [71]:
a = numpy.arange(8)
print(a)
print()

b = a.reshape((2,4))
print(b)
print()

b[0,0] = -42

print("b changed:")
print(b)
print()

print("but so did a:")
print(a)
print()

[0 1 2 3 4 5 6 7]

[[0 1 2 3]
 [4 5 6 7]]

b changed:
[[-42   1   2   3]
 [  4   5   6   7]]

but so did a:
[-42   1   2   3   4   5   6   7]



The `base` attribute in numpy indicates if a variable is pointing to it's own memory or to the memory of another variable. If a variable's `base` is None, then it doesn't point to the memory of another variable. 

In [72]:
print(a.base)

None


In [73]:
print(b.base)
print(b.base is a)

[-42   1   2   3   4   5   6   7]
True


To avoid a shallow copy, use the numpy function copy() to create a deep copy that creates a new location in memory:

In [74]:
a = numpy.arange(8)
print(a)
print()

b = a.copy()
print(b)
print()

b[0] = -42

print("b changed:")
print(b)
print()

print("but because of the copy() function, a did not:")
print(a)
print()

[0 1 2 3 4 5 6 7]

[0 1 2 3 4 5 6 7]

b changed:
[-42   1   2   3   4   5   6   7]

but because of the copy() function, a did not:
[0 1 2 3 4 5 6 7]



## 2.4 Multi-Dimensional Array Indexing

### 2.4.1 Indexing a Single Element
We can use index along different dimensions to retrieve a single element from a multi-dimensional array:

In [80]:
c = numpy.random.uniform(-0.5, .5, (3,4,5))
print(c)
print("========")
print(c[1,2,0])

[[[-0.09171478  0.03815122  0.0769393  -0.0186474  -0.02879786]
  [ 0.27008586  0.43239121  0.16775992 -0.16776555 -0.47838786]
  [ 0.11922403 -0.2895955  -0.27858853 -0.02261327 -0.21449651]
  [-0.48088506 -0.33330026  0.12056694  0.03240735  0.22059486]]

 [[-0.27648989 -0.3931822  -0.08882596 -0.27294667 -0.09204516]
  [ 0.04539901  0.17406611 -0.04413302  0.40963122  0.10173599]
  [-0.40417385  0.41587272  0.34540421  0.27039551  0.42396104]
  [ 0.15398676 -0.34981655  0.46322576  0.04058355 -0.015129  ]]

 [[-0.35963323 -0.49101064  0.04427304  0.05641291  0.31294871]
  [ 0.08373862 -0.35526359 -0.45286147 -0.0182546  -0.10972306]
  [-0.4393067   0.27599387 -0.20526863  0.24645784 -0.06376668]
  [ 0.16029205  0.10792564  0.17380371 -0.40808579 -0.30710254]]]
-0.4041738472847247


In [81]:
print(c[1])
print('------------------------------------')
print(c[1][2])
print('------------------------------------')
print(c[1][2][0])

[[-0.27648989 -0.3931822  -0.08882596 -0.27294667 -0.09204516]
 [ 0.04539901  0.17406611 -0.04413302  0.40963122  0.10173599]
 [-0.40417385  0.41587272  0.34540421  0.27039551  0.42396104]
 [ 0.15398676 -0.34981655  0.46322576  0.04058355 -0.015129  ]]
------------------------------------
[-0.40417385  0.41587272  0.34540421  0.27039551  0.42396104]
------------------------------------
-0.4041738472847247


### 2.4.2 Slicing

We can fetch all the elements along a specific dimension using `:` opertaor:

In [82]:
z = numpy.arange(24).reshape((6, 4))
print( z )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [83]:
# Fetching all the elements in the first row:
print( z[0, :] )

[0 1 2 3]


In [84]:
# Fetching all the elements in the third column:
print( z[:, 2] )

[ 2  6 10 14 18 22]


We can alternatively use the `:` operator to retrieve specific slices of an array: 

In [85]:
print(z)
print('-----------------------')
print( z[2:5, 1:3] )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
-----------------------
[[ 9 10]
 [13 14]
 [17 18]]


In [86]:
print( z[:3,-3:-1] )

[[ 1  2]
 [ 5  6]
 [ 9 10]]


## Exercise 2.4

Generate a $5\times 5 \times 5$ 3D array of random numbers between -10.0 and 10.0. Reshape it to a $5 \times 25$ matrix. Extract the last 10 elements of the first two rows of this matrix.


In [124]:
# a = numpy.random.uniform(-10, 10, 125).reshape(5, 5, 5)
a
b = a.reshape((5, 25))
print(b)
b[0: 2, -10:]

[[ 7.24724908  7.36372201  7.41951925 -7.08113037  2.22680094  4.58280492
  -7.9906954  -9.55548871  3.6946573  -8.47238147  8.94945661  9.06532164
   4.73465198  8.26205404  5.67159961  9.97933228  0.88498029 -9.73457351
  -5.65161035 -5.96834139 -4.97139609  2.31867198 -7.15577262 -0.1392086
   0.159159  ]
 [ 1.87027388  5.99577848  6.83560034  1.9692705  -9.07577443 -5.26603563
   4.82190032  7.70264847  7.99859993  2.01164771 -3.69325116  0.45911635
   1.96840239  1.54043986  6.21704092 -4.06234936  3.16825702  9.53438515
   7.27684551 -5.84722721 -1.6065725   3.42432941  8.66253419 -3.61687124
   7.9817914 ]
 [-2.12043428 -1.02442746  0.82031302 -2.39957642  1.87407046 -8.92539647
   3.44595178  5.09567372  6.82324917 -1.61293944  2.11353713  8.93291602
   6.86954475 -0.63699969  7.3689999  -8.99296426  9.98351137 -8.12372002
   2.17044473 -6.77736098 -4.96277104 -4.62723794  2.92031341 -3.89011855
  -9.89355245]
 [ 3.96598366 -7.10665053 -7.01490905 -6.99125112 -0.61215831  4.708

array([[ 9.97933228,  0.88498029, -9.73457351, -5.65161035, -5.96834139,
        -4.97139609,  2.31867198, -7.15577262, -0.1392086 ,  0.159159  ],
       [-4.06234936,  3.16825702,  9.53438515,  7.27684551, -5.84722721,
        -1.6065725 ,  3.42432941,  8.66253419, -3.61687124,  7.9817914 ]])

### 2.4.3 Boolean Indexing
We can use boolean indexing to retrieve the lements of an array which satisfy a certain condition. Note that the ourput will be a vector (i.e. a one dimensional array).

In [125]:
a = numpy.random.normal(0,5, [3,5])
print(a)

[[-1.05804772 -3.76735545  2.89857176 -2.86418916  1.04390386]
 [-3.10974883  9.74044518  1.46437859 -2.92301334 -5.12986494]
 [ 4.45612104  2.86201056  2.03528868  7.73677771  0.72951827]]


In [126]:
b = a[a<0]
print(b, b.shape)

[-1.05804772 -3.76735545 -2.86418916 -3.10974883 -2.92301334 -5.12986494] (6,)


### 2.4.4 Using `ix_` function
For more complext indexing, we can use `ix_` from numpy. This function constructs an open mesh from multiple sequences and can be used to retrieve arbitrary dimensions of a multi-dimensional array. 

In [127]:
a = numpy.random.normal(0,5, [3,5])
print(a)
print('-----------------')
print(a[numpy.ix_([0,2], [1,2,4])])


[[-13.99172346  -0.39263895   3.23819923   0.03950132  -2.84321023]
 [-13.98064148   3.94497455  -3.39169233   1.1347712   -4.80366509]
 [ -3.1207512    0.96126077  -5.54801497  -2.56337217   0.2675832 ]]
-----------------
[[-0.39263895  3.23819923 -2.84321023]
 [ 0.96126077 -5.54801497  0.2675832 ]]



For complete information about indexing see http://docs.scipy.org/doc/numpy/user/basics.indexing.html.


## 2.5 An example of indexing in RGB images

An RGB image is composed of three color channels: Red (R), Green (G), and Blue (B). Each of these channels can be thought of as a 2D array (or matrix) where each entry in the matrix corresponds to the intensity of that color for a particular pixel in the image. When these channels are combined, they form a 3D array that represents the RGB image. Each entry in the 3D array is an integer value between 0 and 255 (for an 8-bit image), indicating the intensity of the color:
- 0 represents no intensity (black).
- 255 represents full intensity.

The 3D array representing an RGB image has dimensions (height, width, 3), where:

- height is the number of pixels in the vertical direction of the image.
- width is the number of pixels in the horizontal direction of the image.
- 3 represents the three color layers (R, G, B). The first layer (or depth slice) of the 3D array corresponds to the Red channel. The second layer corresponds to the Green channel. The third layer corresponds to the Blue channel.


In [129]:
import matplotlib.pyplot as plt
color_image = plt.imread('lena_color.bmp')
plt.imshow(color_image)
print(color_image.shape, color_image.dtype)

FileNotFoundError: [Errno 2] No such file or directory: 'lena_color.bmp'


To access the RGB values of a specific pixel at (x, y) coordinates:

- Red value: array[y, x, 0]
- Green value: array[y, x, 1]
- Blue value: array[y, x, 2]

We can use array indexing to retrieve different the intesities of different color plans in an RGB image:

In [ ]:
# retrieving and showing the intesities of the red layer for all pixels
red_plane = numpy.zeros(color_image.shape, dtype='uint8')
red_plane[:,:,0] = color_image[:,:,0]
plt.imshow(red_plane)

In [ ]:
# retrieving and showing the intesities of the green layer for all pixels
green_plane = numpy.zeros(color_image.shape, dtype='uint8')
green_plane[:,:,1] = color_image[:,:,1]
plt.imshow(green_plane)

In [ ]:
# retrieving and showing the intesities of the blue layer for all pixels
blue_plane = numpy.zeros(color_image.shape, dtype='uint8')
blue_plane[:,:,2] = color_image[:,:,2]
plt.imshow(blue_plane)

We can also use array indexing to crop an RGB image:

In [ ]:
# Cropping the image using array indexing
plt.imshow(color_image[100:400, 100:355, :])